kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang:1.16
  command:
    - ls -la
    - echo $PATH
    - go version
    - go mod tidy
    - go mod vendor
    - go test ./...
    - go build

- name: build
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/Genesic/URLShortenerDemo
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username: Genesic
    password:
      from_secret: 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
