version: '3.7'
services:
  app:
    image: app
    build: .
    restart: always
    stdin_open: true
    tty: true
    command: ["./wait-for-it.sh", "db:3306", "--", "/app/start.sh"]
    environment:
      db_source: root:abcd1234@tcp(db:3306)/shorten?collation=utf8mb4_unicode_ci&parseTime=True&loc=Local
      port: 8080
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: shorten
    ports:
      - 3306:3306